In [2]:
import numpy as np
import indydcp_client as client
import json
from indy_program_maker import JsonProgramComponent, PickNPlace

# Connect to Indy by IndyDCP

In [3]:
bind_ip   = "192.168.3.105"
name = "NRMK-Indy7"

# indy_vac = client.IndyDCPClient(bind_ip, "192.168.3.129", name)
# indy_vac.connect()

# indy_vac = client.IndyDCPClient(bind_ip, "192.168.3.147", name)
# indy_vac.connect()

# indy_taka = client.IndyDCPClient(bind_ip, "192.168.3.112", name)
# indy_taka.connect()

indy_gripper = client.IndyDCPClient(bind_ip, "192.168.3.106", name)
indy_gripper.connect()

# Program maker
prog = JsonProgramComponent()

Connect: Bind IP (192.168.3.105), Server IP (192.168.3.106)


In [11]:
indy_gripper.disconnect()

Disconnected


# Indy Gripper - set wall

In [ ]:
 def open_gripper(prog):
    prog.add_digital_out(9, 1)
    prog.add_digital_out(8, 0)
    prog.add_wait(2)    
        
def close_gripper(prog):
    prog.add_digital_out(8, 1)
    prog.add_digital_out(9, 0)
    prog.add_wait(2)

def go_down(task_pos, i):
    one_step = 0.032
    task_pos[2] = task_pos[2] - one_step
    return task_pos

def get_handle_pos(pos1, pos2, i):
#     i~0:9
    pos = pos1 + ((pos2 - pos1)/9)*i  
    return pos
        

In [6]:
def indy_gripper_setting_wall(vel=2):
    with open('teach-gripper-set.json') as json_file:
        tp_grip_set = json.load(json_file)

    prog = JsonProgramComponent(policy=0, resume_time=2)
    open_gripper(prog)
    prog.add_move_home()
    
    # First Long Wall
    # Pick     
    prog.add_joint_move_to(tp_grip_set['j_pre_pick_1'], vel)
    prog.add_task_move_to(tp_grip_set['t_pick_1'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_pickup_1'], vel)
    
    # Place     
    prog.add_move_home()
    prog.add_joint_move_to(tp_grip_set['j_pre_place_1'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_1-1'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_1-2'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_1-3'], vel)
    open_gripper(prog)
    
    # Reposition    
    prog.add_task_move_to(tp_grip_set['t_reposition_1-1'], vel)
    prog.add_task_move_to(tp_grip_set['t_reposition_1-2'], vel)
    prog.add_task_move_to(tp_grip_set['t_reposition_1-3'], vel)
    prog.add_task_move_to(tp_grip_set['t_reposition_1-4'], vel)
    prog.add_move_home()
    
    
    # Second, Short Wall     
    # Pick
    prog.add_joint_move_to(tp_grip_set['j_pre_pick_2'], vel)
    prog.add_task_move_to(tp_grip_set['t_pick_2'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_pickup_2'], vel)
    
    
    # Place     
    prog.add_move_home()
    prog.add_joint_move_to(tp_grip_set['j_pre_place_2'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_2-1'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_2-2'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_2-3'], vel)
    open_gripper(prog)
    
    # Reposition    
    prog.add_task_move_to(tp_grip_set['t_reposition_2-1'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_reposition_2-2'], vel)
    open_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_reposition_2-3'], vel)
    prog.add_move_home()
    
    # Third, Short Wall     
    # Pick
    prog.add_joint_move_to(tp_grip_set['j_pre_pick_3'], vel)
    prog.add_task_move_to(tp_grip_set['t_pick_3'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_pickup_3'], vel)
    
    
    # Place     
    prog.add_move_home()
    prog.add_joint_move_to(tp_grip_set['j_pre_place_3'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_3-1'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_3-2'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_3-3'], vel)
    open_gripper(prog)
    
    # Reposition    
    prog.add_task_move_to(tp_grip_set['t_reposition_3-1'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_reposition_3-2'], vel)
    open_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_reposition_3-3'], vel)
    prog.add_move_home()
    
    
    
    # Forth, Long Wall
    # Pick
    prog.add_joint_move_to(tp_grip_set['j_pre_pick_4'], vel)
    prog.add_task_move_to(tp_grip_set['t_pick_4'], vel)
    close_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_pickup_4'], vel)
    
    # Place     
    prog.add_joint_move_to(tp_grip_set['j_pre_place_4'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_4-1'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_4-2'], vel)
    prog.add_task_move_to(tp_grip_set['t_place_4-3'], vel)
    open_gripper(prog)
    prog.add_task_move_to(tp_grip_set['t_post_place_4'], vel)
    prog.add_move_home()
    prog.add_joint_move_to(tp_grip_set['j_stay_back_1'], vel)
    prog.add_joint_move_to(tp_grip_set['j_stay_back_2'], vel)
   
            
    return json.dumps(prog.json_program)
   
    


In [9]:
prog_gripper_setting_wall = indy_gripper_setting_wall()
indy_gripper.set_and_start_json_program(prog_gripper_setting_wall)

In [10]:
indy_gripper.stop_current_program()  # 디버그 할 때는 로봇 프로그램 중 이거 쓰면 프로그램 정지됨


# Load and Save JSON

In [43]:
with open('teach-gripper-set.json', 'w') as fp:
    json.dump(indy_grip_teaching, fp)

# Teaching information

In [30]:
indy_vac.get_joint_pos()

array([ 3.32606090e+01, -2.41158542e+01, -9.87019897e+01, -2.39300044e-03,
       -5.73039240e+01, -6.96692020e+01])

In [34]:
indy_vac_teaching

{'loading': {'j_pre_pick': [-46.3865,
   -38.4961,
   -74.0504,
   -0.932206,
   -67.5403,
   -59.7],
  'j_pick': [-46.3864, -50.3103, -82.7917, -1.18125, -46.9428, -59.246],
  't_pickup1': [0.274896,
   -0.568617,
   0.189142,
   0.377864,
   -179.223149,
   13.638134],
  't_pickup2': [0.27486599,
   -0.56858698,
   0.29972155,
   0.35848156,
   -179.21393662,
   13.63670113],
  'j_load0': [-287.70847200000003],
  'j_load1': [-6.92393035,
   3.07644261,
   -123.36016532,
   3.41446385,
   -56.96177338,
   -65.51745681],
  'j_load2': [34.36586904,
   -3.79849984,
   -114.40966921,
   3.92869999,
   -58.43845497,
   -65.517512],
  'j_load3': [-207.72166433999996],
  'j_load4': [33.63, -38.52, -107.16, -0.01, -34.3, -69.27],
  'j_load5': [33.26, -39.06, -107.23, -0.0, -33.68, -69.67],
  't_push': [0.502, 0.10632, 0.1222, 0.08, 179.97, 102.94],
  'j_stayback1': [33.26, -24.12, -98.7, 0.0, -57.3, -69.67],
  'j_stayback2': [2.0, 0.5, -124.73, 5.27, -53.24, -77.9],
  'j_stayback3': [-57.75, 

In [24]:
indy_gripper.get_joint_pos()

array([-3.78224321e+01, -6.25131150e+01, -3.86452263e+01,  1.35969407e-01,
       -7.81101824e+01, -2.03274754e+02])

In [40]:
indy_gripper.get_task_pos()

array([   0.48795174,   -0.60816147,    0.2194172 ,   -0.39758117,
       -179.27929279,  165.23013094])

[7.93117555, -28.7473619, -75.6819998, 0.00429663328, -75.5320392, -99.9127681]

In [42]:


indy_grip_teaching = {
    'j_pre_pick_1':[ 5.20847743e+01, -2.31478756e+01, -9.01812290e+01, -2.56166364e-02,
       -6.67276938e+01, -2.53221810e+01],
    't_pick_1': [4.68250654e-01, 2.75785695e-01, 2.56964844e-01, 3.31428278e-02,
       1.79615929e+02, 7.57714081e+01],
    't_pickup_1': [ 4.67832118e-01,  2.75409631e-01,  3.55252971e-01, -5.76883533e-02,
        1.79761948e+02,  7.58083955e+01],
    'j_pre_place_1': [-4.90302119e+01, -4.99298651e+01, -6.08416042e+01, -9.04468499e-02,
       -6.88940671e+01, -1.25230109e+02],
    't_place_1-1':[ 3.02319944e-01, -6.31185406e-01,  1.76797753e-01,  4.19028688e-01,
       -1.79606383e+02,  7.62166607e+01],
    't_place_1-2':[ 3.00638908e-01, -6.33429557e-01,  1.61147982e-01,  5.34354793e-01,
       -1.79521625e+02,  7.56340394e+01],
    't_place_1-3':[ 3.01259380e-01, -6.33973812e-01,  1.49337921e-01,  8.81265920e-02,
       -1.79404060e+02,  7.56451858e+01],
    't_reposition_1-1':[ 3.01978321e-01, -6.34741833e-01,  1.28723080e-01,  3.35080752e-01,
       -1.79246612e+02,  7.56599383e+01],
    't_reposition_1-2':[ 3.03006647e-01, -6.39472784e-01,  1.29822961e-01,  4.01927218e-01,
       -1.79194227e+02,  7.57331423e+01],
    't_reposition_1-3':[ 3.02255152e-01, -6.33913536e-01,  1.29447514e-01,  3.84550318e-01,
       -1.79215479e+02,  7.56706469e+01],
    't_reposition_1-4':[   0.30253168,   -0.63424529,    0.23349826,    0.45434962,
       -179.16398243,   75.6633814 ],
    'j_pre_pick_2':[-1.02739419e+01, -4.97840011e+01, -7.35607759e+01,  1.53917369e-02,
       -5.64618947e+01,  3.61493706e+00],
    't_pick_2':[ 5.93385356e-01, -2.95120456e-01,  1.22337742e-01,  1.79957945e+02,
        3.55865361e-02,  1.65227701e+02],
    't_pickup_2':[ 5.92929198e-01, -2.95029274e-01,  2.02000727e-01,  1.79962207e+02,
       -4.51184086e-02,  1.65230880e+02],
    'j_pre_place_2':[-3.78224321e+01, -6.25131150e+01, -3.86452263e+01,  1.35969407e-01,
       -7.81101824e+01, -2.03274754e+02],
    't_place_2-1':[ 4.77715875e-01, -6.03348862e-01,  1.61427745e-01, -1.04551485e-01,
       -1.79386188e+02,  1.65415311e+02],
    't_place_2-2':[ 4.86946132e-01, -6.05015792e-01,  1.57485242e-01, -2.66706197e-01,
       -1.78966515e+02,  1.65284621e+02],
    't_place_2-3': [ 4.88016515e-01, -6.06196592e-01,  1.44442137e-01, -3.89747363e-01,
       -1.79307218e+02,  1.65235365e+02],
    't_reposition_2-1': [ 4.88200288e-01, -6.06519109e-01,  1.28260687e-01, -4.38369054e-01,
       -1.79191282e+02,  1.65232805e+02],
    't_reposition_2-2':[ 4.88281350e-01, -6.08094685e-01,  1.28251266e-01, -4.13538115e-01,
       -1.79229973e+02,  1.65257497e+02],
    't_reposition_2-3':[   0.48795174,   -0.60816147,    0.2194172 ,   -0.39758117,
       -179.27929279,  165.23013094],
    'j_pre_pick_3':[-5.21646295e+00, -2.14096296e+01, -1.32144553e+02,  6.93443978e-02,
       -2.64820001e+01,  9.51894628e+00],
    't_pick_3':[ 3.02485940e-01, -2.16981228e-01,  1.18876288e-01,  1.79946491e+02,
        2.06305656e-01,  1.65181940e+02],
    't_pickup_3':[ 3.02331837e-01, -2.16953481e-01,  1.78995202e-01,  1.79944459e+02,
        1.97808861e-01,  1.65184494e+02],
    'j_pre_place_3':[-5.24937199e+01, -3.34791552e+01, -9.64888795e+01, -6.49933768e-02,
       -4.98130995e+01, -3.75150473e+01],
    't_place_3-1':[ 1.66903579e-01, -5.24094005e-01,  1.59659956e-01, -1.79842074e+02,
        1.26919156e-01,  1.65063893e+02],
    't_place_3-2':[ 1.54160264e-01, -5.21124868e-01,  1.58902540e-01, -1.79886741e+02,
        6.54648790e-02,  1.65369886e+02],
    't_place_3-3':[ 1.54052843e-01, -5.21042494e-01,  1.40447646e-01, -1.79861340e+02,
        8.77483700e-02,  1.65379132e+02],
    't_reposition_3-1':[ 1.54529086e-01, -5.21638853e-01,  1.26119577e-01, -1.79743854e+02,
        2.38055873e-01,  1.65381931e+02],
    't_reposition_3-2':[ 1.53938042e-01, -5.23165043e-01,  1.26106297e-01, -1.79790915e+02,
        1.81045755e-01,  1.65358022e+02],
    't_reposition_3-3':[ 1.54067390e-01, -5.21293377e-01,  1.99801940e-01, -1.79763669e+02,
        2.08492774e-01,  1.65358892e+02],
    'j_pre_pick_4':[ 4.26730775e+01, -1.48747619e+01, -1.04114299e+02,  4.36733737e-02,
       -6.02593027e+01, -3.35744907e+01],
    't_pick_4':[4.38633190e-01, 1.50908562e-01, 2.59924464e-01, 4.26836916e-01,
       1.79295948e+02, 7.62229004e+01],
    't_pickup_4':[4.38480605e-01, 1.50673102e-01, 3.56105928e-01, 7.19327696e-04,
       1.79995635e+02, 7.62092966e+01],
    'j_pre_place_4':[-3.79630298e+01, -3.77053505e+01, -8.36968439e+01, -1.53373492e-02,
       -5.86014549e+01, -1.14989274e+02],
    't_place_4-1':[ 3.36936214e-01, -5.01022326e-01,  1.64485073e-01,  4.18718124e-01,
       -1.79801814e+02,  7.58594520e+01],
    't_place_4-2':[ 3.39616213e-01, -4.90721856e-01,  1.64563518e-01,  4.33191323e-01,
       -1.79799052e+02,  7.59263011e+01],
    't_place_4-3':[ 3.40133048e-01, -4.91389795e-01,  1.46968674e-01,  6.40689363e-01,
       -1.79703099e+02,  7.59146353e+01],
    't_post_place_4':[   0.34007493,   -0.49134307,    0.21608517,    0.61328803,
       -179.71362828,   75.91519987],
    'j_stay_back_1':[ 4.08993757e+01,  5.69277929e+00, -9.79299952e+01,  2.36586769e-02,
       -7.51942368e+01, -7.91959253e+01],
    'j_stay_back_2':[  72.24595756,    3.00417057, -103.34552859,    2.40426545,
        -76.25539647,  -79.19592527]
}


indy_grip_teaching

{'j_pre_pick_1': [52.0847743,
  -23.1478756,
  -90.181229,
  -0.0256166364,
  -66.7276938,
  -25.322181],
 't_pick_1': [0.468250654,
  0.275785695,
  0.256964844,
  0.0331428278,
  179.615929,
  75.7714081],
 't_pickup_1': [0.467832118,
  0.275409631,
  0.355252971,
  -0.0576883533,
  179.761948,
  75.8083955],
 'j_pre_place_1': [-49.0302119,
  -49.9298651,
  -60.8416042,
  -0.0904468499,
  -68.8940671,
  -125.230109],
 't_place_1-1': [0.302319944,
  -0.631185406,
  0.176797753,
  0.419028688,
  -179.606383,
  76.2166607],
 't_place_1-2': [0.300638908,
  -0.633429557,
  0.161147982,
  0.534354793,
  -179.521625,
  75.6340394],
 't_place_1-3': [0.30125938,
  -0.633973812,
  0.149337921,
  0.088126592,
  -179.40406,
  75.6451858],
 't_reposition_1-1': [0.301978321,
  -0.634741833,
  0.12872308,
  0.335080752,
  -179.246612,
  75.6599383],
 't_reposition_1-2': [0.303006647,
  -0.639472784,
  0.129822961,
  0.401927218,
  -179.194227,
  75.7331423],
 't_reposition_1-3': [0.302255152,
  -0.